#Default position config for kuka kr210 ros2_control
default_position:
  joint_1: 0.0
  joint_2: 0.0
  joint_3: 0.0
  joint_4: 0.0
  joint_5: 0.0
  joint_6: 0.0
  left_gripper_finger_joint: 0.0
  right_gripper_finger_joint: 0.0
  